// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYuNiTgNmXUng1NmFsj7VTYAKgfPjv36Y',
    appId: '1:984392892238:web:a512c1346e69638a35a81f',
    messagingSenderId: '984392892238',
    projectId: 'my-business-ce9ed',
    authDomain: 'my-business-ce9ed.firebaseapp.com',
    storageBucket: 'my-business-ce9ed.firebasestorage.app',
    measurementId: 'G-H0M6CTXZPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDle94abUbNT4fxrruThTKfes986u7A9jQ',
    appId: '1:984392892238:android:545d590feecb6a8635a81f',
    messagingSenderId: '984392892238',
    projectId: 'my-business-ce9ed',
    storageBucket: 'my-business-ce9ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAD-iB7sWnye2_ncQwMxsNcHpy95TkYZE',
    appId: '1:984392892238:ios:daf8110d478ef0cd35a81f',
    messagingSenderId: '984392892238',
    projectId: 'my-business-ce9ed',
    storageBucket: 'my-business-ce9ed.firebasestorage.app',
    iosBundleId: 'com.example.myBusiness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAD-iB7sWnye2_ncQwMxsNcHpy95TkYZE',
    appId: '1:984392892238:ios:daf8110d478ef0cd35a81f',
    messagingSenderId: '984392892238',
    projectId: 'my-business-ce9ed',
    storageBucket: 'my-business-ce9ed.firebasestorage.app',
    iosBundleId: 'com.example.myBusiness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYuNiTgNmXUng1NmFsj7VTYAKgfPjv36Y',
    appId: '1:984392892238:web:58b17a0cccc174d335a81f',
    messagingSenderId: '984392892238',
    projectId: 'my-business-ce9ed',
    authDomain: 'my-business-ce9ed.firebaseapp.com',
    storageBucket: 'my-business-ce9ed.firebasestorage.app',
    measurementId: 'G-1GFLZ4RWHW',
  );

}